// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLoading: typeof import('./src/components/common/AppLoading.vue')['default']
    CustomIcon: typeof import('./src/components/custom/CustomIcon.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HoverContainer: typeof import('./src/components/common/HoverContainer.vue')['default']
    'IconClarity:bellLine': typeof import('~icons/clarity/bell-line')['default']
    IconCustomLogo: typeof import('~icons/custom/logo')['default']
    'IconIc:outlineDarkMode': typeof import('~icons/ic/outline-dark-mode')['default']
    'IconIc:outlineLightMode': typeof import('~icons/ic/outline-light-mode')['default']
    'IconMaterialSymbols:fullscreen': typeof import('~icons/material-symbols/fullscreen')['default']
    'IconMaterialSymbols:fullscreenExit': typeof import('~icons/material-symbols/fullscreen-exit')['default']
    'IconMdi:github': typeof import('~icons/mdi/github')['default']
    'IconRi:search2Line': typeof import('~icons/ri/search2-line')['default']
    NaiveProvider: typeof import('./src/components/common/NaiveProvider.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigGlobal: typeof import('naive-ui')['NConfigGlobal']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NSapce: typeof import('naive-ui')['NSapce']
    NSpace: typeof import('naive-ui')['NSpace']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/common/SvgIcon.vue')['default']
    TheIcon: typeof import('./src/components/custom/TheIcon.vue')['default']
    Tooltip: typeof import('./src/components/common/Tooltip.vue')['default']
  }
}
